INSERT INTO "profiles_usstate" ("name", "code") VALUES ('Alabama', 'AL');
INSERT INTO "profiles_usstate" ("name", "code") VALUES ('Alaska', 'AK');
INSERT INTO "profiles_usstate" ("name", "code") VALUES ('Arizona', 'AZ');
INSERT INTO "profiles_usstate" ("name", "code") VALUES ('Arkansas', 'AR');
INSERT INTO "profiles_usstate" ("name", "code") VALUES ('California', 'CA');
INSERT INTO "profiles_usstate" ("name", "code") VALUES ('Colorado', 'CO');
INSERT INTO "profiles_usstate" ("name", "code") VALUES ('Connecticut', 'CT');
INSERT INTO "profiles_usstate" ("name", "code") VALUES ('Delaware', 'DE');
INSERT INTO "profiles_usstate" ("name", "code") VALUES ('District of Columbia', 'DC');
INSERT INTO "profiles_usstate" ("name", "code") VALUES ('Florida', 'FL');
INSERT INTO "profiles_usstate" ("name", "code") VALUES ('Georgia', 'GA');
INSERT INTO "profiles_usstate" ("name", "code") VALUES ('Hawaii', 'HI');
INSERT INTO "profiles_usstate" ("name", "code") VALUES ('Idaho', 'ID');
INSERT INTO "profiles_usstate" ("name", "code") VALUES ('Illinois', 'IL');
INSERT INTO "profiles_usstate" ("name", "code") VALUES ('Indiana', 'IN');
INSERT INTO "profiles_usstate" ("name", "code") VALUES ('Iowa', 'IA');
INSERT INTO "profiles_usstate" ("name", "code") VALUES ('Kansas', 'KS');
INSERT INTO "profiles_usstate" ("name", "code") VALUES ('Kentucky', 'KY');
INSERT INTO "profiles_usstate" ("name", "code") VALUES ('Louisiana', 'LA');
INSERT INTO "profiles_usstate" ("name", "code") VALUES ('Maine', 'ME');
INSERT INTO "profiles_usstate" ("name", "code") VALUES ('Maryland', 'MD');
INSERT INTO "profiles_usstate" ("name", "code") VALUES ('Massachusetts', 'MA');
INSERT INTO "profiles_usstate" ("name", "code") VALUES ('Michigan', 'MI');
INSERT INTO "profiles_usstate" ("name", "code") VALUES ('Minnesota', 'MN');
INSERT INTO "profiles_usstate" ("name", "code") VALUES ('Mississippi', 'MS');
INSERT INTO "profiles_usstate" ("name", "code") VALUES ('Missouri', 'MO');
INSERT INTO "profiles_usstate" ("name", "code") VALUES ('Montana', 'MT');
INSERT INTO "profiles_usstate" ("name", "code") VALUES ('Nebraska', 'NE');
INSERT INTO "profiles_usstate" ("name", "code") VALUES ('Nevada', 'NV');
INSERT INTO "profiles_usstate" ("name", "code") VALUES ('New Hampshire', 'NH');
INSERT INTO "profiles_usstate" ("name", "code") VALUES ('New Jersey', 'NJ');
INSERT INTO "profiles_usstate" ("name", "code") VALUES ('New Mexico', 'NM');
INSERT INTO "profiles_usstate" ("name", "code") VALUES ('New York', 'NY');
INSERT INTO "profiles_usstate" ("name", "code") VALUES ('North Carolina', 'NC');
INSERT INTO "profiles_usstate" ("name", "code") VALUES ('North Dakota', 'ND');
INSERT INTO "profiles_usstate" ("name", "code") VALUES ('Ohio', 'OH');
INSERT INTO "profiles_usstate" ("name", "code") VALUES ('Oklahoma', 'OK');
INSERT INTO "profiles_usstate" ("name", "code") VALUES ('Oregon', 'OR');
INSERT INTO "profiles_usstate" ("name", "code") VALUES ('Pennsylvania', 'PA');
INSERT INTO "profiles_usstate" ("name", "code") VALUES ('Rhode Island', 'RI');
INSERT INTO "profiles_usstate" ("name", "code") VALUES ('South Carolina', 'SC');
INSERT INTO "profiles_usstate" ("name", "code") VALUES ('South Dakota', 'SD');
INSERT INTO "profiles_usstate" ("name", "code") VALUES ('Tennessee', 'TN');
INSERT INTO "profiles_usstate" ("name", "code") VALUES ('Texas', 'TX');
INSERT INTO "profiles_usstate" ("name", "code") VALUES ('Utah', 'UT');
INSERT INTO "profiles_usstate" ("name", "code") VALUES ('Vermont', 'VT');
INSERT INTO "profiles_usstate" ("name", "code") VALUES ('Virginia', 'VA');
INSERT INTO "profiles_usstate" ("name", "code") VALUES ('Washington', 'WA');
INSERT INTO "profiles_usstate" ("name", "code") VALUES ('West Virginia', 'WV');
INSERT INTO "profiles_usstate" ("name", "code") VALUES ('Wisconsin', 'WI');
INSERT INTO "profiles_usstate" ("name", "code") VALUES ('Wyoming', 'WY');

